events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name _;


        # CORS
        add_header Access-Control-Allow-Origin http://localhost:5173 always;
        add_header Access-Control-Allow-Credentials true always;
        add_header Access-Control-Allow-Methods "GET, POST, PUT, PATCH, DELETE, OPTIONS" always;
        add_header Access-Control-Allow-Headers "Authorization, Content-Type" always;

        # Handle preflight
        if ($request_method = OPTIONS) {
            return 204;
        }


        # ========================================
        # ACCOUNT SERVICE (Port 3001)
        # ========================================
        location /api/v1/users/  {
            proxy_pass http://account-service:3001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Authorization $http_authorization;
        }

        location /api/v1/admin {
            proxy_pass http://account-service:3001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Authorization $http_authorization;
        }

        # ========================================
        # ACADEMIC SERVICE (Port 3000)
        # ========================================
        location /api/v1/lecturers {
            proxy_pass http://academic-service:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Authorization $http_authorization;
        }

        location /api/v1/enrollment/ {
            proxy_pass http://academic-service:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Authorization $http_authorization;
        }

        location /api/v1/students/ {
            proxy_pass http://academic-service:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Authorization $http_authorization;
        }

        

        # ========================================
        # COURSE SERVICE (Sửa lại để tránh 404)
        # ========================================
        location /api/v1/courses/ {
            resolver 127.0.0.11 valid=30s;
            set $upstream_course course-service;

            # CHỈ để tên host và port, KHÔNG để thêm path phía sau
            proxy_pass http://$upstream_course:3002;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Authorization $http_authorization;
            proxy_pass_header Authorization;

        }

        location /api/v1/materials/ {
           resolver 127.0.0.11 valid=30s;
            set $upstream_course course-service;
            proxy_pass http://$upstream_course:3002;
            
            client_max_body_size 50M; 
            
            # Các header bắt buộc phải có để Multer hoạt động qua Proxy
            proxy_set_header Host $host;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_request_buffering off;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Authorization $http_authorization;
        }
    }
}