export enum AuditAction {
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILED = 'LOGIN_FAILED',
  LOGOUT = 'LOGOUT',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED',
  ACCOUNT_CREATED = 'ACCOUNT_CREATED',
  ACCOUNT_DISABLED = 'ACCOUNT_DISABLED',
  ROLE_CHANGED = 'ROLE_CHANGED',
}